spring:
  application:
    name: eureka-server

server:
  port: ${PORT:8761}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    eureka-server-connect-timeout-seconds: 60 # Время ожидания (1 минута) до истечения тайм-аута соединения с Eureka Server
    eureka-service-url-poll-interval-seconds: 15 #  каждые 15 секунд запрашивать изменения об информации с сервера
    use-dns-for-fetching-service-urls: false #  запретите dns и укажите явный маршрут к серверам eureka (serviceUrl)
    prefer-same-zone-eureka: true # использовать сервер eureka в той же зоне
    healthcheck: #  Для клиента включим healthcheck
      enabled: true
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka/

  server:
      renewal-percent-threshold: 0.85 # 5 если возникнут проблемы в сети или наш сервер выйдет из строя мы хотим запретить клиент

  instance:
    hostname: my-eureka-server.com
    metadata-map:
      zone: zone_A # 6.2 использовать сервер eureka в той же зоне
    lease-renewal-interval-in-seconds: 20 # 8 установить время, по которому сервер будет ожидать эхо запрос от клиента о том что он жив (20 секунд)
    lease-expiration-duration-in-seconds: 70 # 9 Если Eureka Server не видел обновления в течение 70 секунд, он удаляет экземпляр из своего реестра
